
apiVersion: 1

datasources:

  # Prometheus como fonte de dados principal. O Grafana busca métricas para montar os dashboards
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"